project:
  type: website
  output-dir: docs

website:
  title: "Joshua Osoro"
  navbar:
    left:
      - href: index.qmd
        text: Qualitative Data Analysis
      - href: index.qmd#quantitative-data
        text: Quantitative Data Analysis
      - href: index.qmd#data-visualization
        text: Data visualization      
      - href: index.qmd#developer  
        text: Web Developer
      - href: index.qmd#contact
        text: Contact

    right: 
      - icon: github
        href: https://github.com/joshuaosoro
      - icon: twitter 
        href: https://twitter.com/@joshuaosoro 

  page-footer: 
    background: light
    left: 
      - text: joshua osoro 
    right:       
      - icon: github
        href: https://github.com/joshuaosoro
      - icon: twitter 
        href: https://twitter.com/@joshuaosoro
      

        

format:
  html:
    theme: litera
    css: styles.css
    toc: true



